#!/usr/bin/env bash
# and advance task in creating and deleting.

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
i=0
while [ $i -eq 0 ]
do
   echo 'To infinity and beyond'
   sleep 2
   trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid; exit' SIGTERM
   trap 'echo "Y U no love me?!"' SIGINT
   trap 'sudo rm /var/run/myscript.pid; exit' SIGQUIT
done
